name: Nice if example

on:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:
  quality_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Peform code quality 
        if: startsWith(github.ref_name, 'feature') && github.event_name == 'push'
        run: echo "Perfoming quality checks on the code"


  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Development Deploy
        if: github.ref_name == 'develop' && github.event_name == 'push'
        run: echo "Deploying the code to development environment"

  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Production Deploy
        if: github.ref_name == 'main' && github.event_name == 'push'
        run: echo "Deploying the code to production environment"


  success_notify:
    needs: ['quality_checks', 'dev_deploy', 'prod_deploy']
    if: always() && !failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify success 
        run: echo "Success email sent to the team"

  error_notify:
    needs: ['quality_checks', 'dev_deploy', 'prod_deploy']
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Failure 
        run: echo "Failure email sent to the team"